# Generated by Django 4.2.29 on 2026-03-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


PUBLIC_DECKS = [
    {
        "title": "English: Food",
        "icon": "🍎",
        "language": "en",
        "words": [
            ("apple", "яблоко", "I eat an apple every morning."),
            ("bread", "хлеб", "Fresh bread smells amazing."),
            ("cheese", "сыр", "This cheese is very soft."),
            ("soup", "суп", "The soup is hot and tasty."),
            ("coffee", "кофе", "She drinks coffee before work."),
            ("salad", "салат", "We ordered a green salad."),
        ],
    },
    {
        "title": "English: Travel",
        "icon": "✈️",
        "language": "en",
        "words": [
            ("airport", "аэропорт", "The airport is twenty minutes away."),
            ("ticket", "билет", "I bought a train ticket online."),
            ("passport", "паспорт", "Keep your passport in a safe place."),
            ("hotel", "отель", "Our hotel is near the beach."),
            ("map", "карта", "This map is easy to read."),
            ("journey", "путешествие", "The journey was long but exciting."),
        ],
    },
    {
        "title": "English: Top Verbs",
        "icon": "📘",
        "language": "en",
        "words": [
            ("be", "быть", "I want to be a designer."),
            ("have", "иметь", "They have two cats."),
            ("go", "идти", "We go to school by bus."),
            ("make", "делать", "Can you make some tea?"),
            ("know", "знать", "Do you know this song?"),
            ("take", "брать", "Take your umbrella with you."),
        ],
    },
    {
        "title": "Deutsch: Essen",
        "icon": "🥨",
        "language": "de",
        "words": [
            ("Apfel", "яблоко", "Ich esse einen Apfel."),
            ("Brot", "хлеб", "Das Brot ist frisch."),
            ("Käse", "сыр", "Der Käse ist sehr lecker."),
            ("Suppe", "суп", "Die Suppe ist heiß."),
            ("Kaffee", "кофе", "Am Morgen trinke ich Kaffee."),
            ("Milch", "молоко", "Die Milch ist im Kühlschrank."),
        ],
    },
    {
        "title": "Deutsch: Reisen",
        "icon": "🧳",
        "language": "de",
        "words": [
            ("Flughafen", "аэропорт", "Der Flughafen ist sehr groß."),
            ("Fahrkarte", "билет", "Ich kaufe eine Fahrkarte."),
            ("Pass", "паспорт", "Mein Pass liegt in der Tasche."),
            ("Hotel", "отель", "Das Hotel ist im Zentrum."),
            ("Karte", "карта", "Hast du eine Karte von Berlin?"),
            ("Reise", "путешествие", "Unsere Reise beginnt morgen."),
        ],
    },
    {
        "title": "Deutsch: Alltag",
        "icon": "🏠",
        "language": "de",
        "words": [
            ("Tisch", "стол", "Das Buch liegt auf dem Tisch."),
            ("Stuhl", "стул", "Der Stuhl ist aus Holz."),
            ("Fenster", "окно", "Bitte öffne das Fenster."),
            ("Schlüssel", "ключ", "Wo ist mein Schlüssel?"),
            ("Tasche", "сумка", "Die Tasche ist schwer."),
            ("Lampe", "лампа", "Die Lampe ist neu."),
        ],
    },
    {
        "title": "Español: Comida",
        "icon": "🌮",
        "language": "es",
        "words": [
            ("manzana", "яблоко", "Como una manzana cada día."),
            ("pan", "хлеб", "El pan está caliente."),
            ("queso", "сыр", "Este queso es muy bueno."),
            ("sopa", "суп", "La sopa está en la mesa."),
            ("café", "кофе", "Necesito café por la mañana."),
            ("ensalada", "салат", "La ensalada tiene tomate."),
        ],
    },
    {
        "title": "Español: Viajes",
        "icon": "🚆",
        "language": "es",
        "words": [
            ("aeropuerto", "аэропорт", "El aeropuerto está lejos."),
            ("billete", "билет", "Tengo un billete para Madrid."),
            ("pasaporte", "паспорт", "Busca tu pasaporte, por favor."),
            ("hotel", "отель", "Nuestro hotel es pequeño."),
            ("mapa", "карта", "Necesito un mapa de la ciudad."),
            ("viaje", "путешествие", "El viaje fue muy divertido."),
        ],
    },
    {
        "title": "Español: Verbos",
        "icon": "📗",
        "language": "es",
        "words": [
            ("ser", "быть", "Quiero ser médico."),
            ("tener", "иметь", "Tenemos una clase hoy."),
            ("ir", "идти", "Voy al trabajo en metro."),
            ("hacer", "делать", "Vamos a hacer la tarea."),
            ("saber", "знать", "No sé la respuesta."),
            ("tomar", "брать", "Puedes tomar mi libro."),
        ],
    },
]


def seed_public_decks(apps, schema_editor):
    Deck = apps.get_model("trainer", "Deck")
    Word = apps.get_model("trainer", "Word")

    for deck_data in PUBLIC_DECKS:
        deck, _ = Deck.objects.get_or_create(
            title=deck_data["title"],
            language=deck_data["language"],
            owner=None,
            defaults={"icon": deck_data["icon"]},
        )
        if deck.icon != deck_data["icon"]:
            deck.icon = deck_data["icon"]
            deck.save(update_fields=["icon"])

        for text, translation, example_sentence in deck_data["words"]:
            word, created = Word.objects.get_or_create(
                deck=deck,
                text=text,
                defaults={"translation": translation, "example_sentence": example_sentence},
            )
            if not created:
                updates = []
                if word.translation != translation:
                    word.translation = translation
                    updates.append("translation")
                if word.example_sentence != example_sentence:
                    word.example_sentence = example_sentence
                    updates.append("example_sentence")
                if updates:
                    word.save(update_fields=updates)


def unseed_public_decks(apps, schema_editor):
    Deck = apps.get_model("trainer", "Deck")
    for deck_data in PUBLIC_DECKS:
        Deck.objects.filter(title=deck_data["title"], language=deck_data["language"], owner=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='flashcard_known_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('flashcards', 'Flashcards'), ('spelling', 'Spelling')], max_length=32)),
                ('session_id', models.CharField(max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_answer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='trainer.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='trainer.word')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(seed_public_decks, unseed_public_decks),
    ]
