# Generated by Django 4.2.29 on 2026-03-29 12:07

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


DEFAULT_ACHIEVEMENTS = [
    {
        "code": "first_review",
        "title": "Первое повторение",
        "description": "Завершите первую сессию интервального повторения.",
        "icon_url": "",
        "condition_type": "first_review",
        "condition_value": 1,
    },
    {
        "code": "streak_3",
        "title": "Серия 3 дня",
        "description": "Заходите в приложение 3 дня подряд.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 3,
    },
    {
        "code": "streak_7",
        "title": "Серия 7 дней",
        "description": "Поддерживайте активность 7 дней подряд.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 7,
    },
    {
        "code": "streak_30",
        "title": "Серия 30 дней",
        "description": "Продержитесь в ударном режиме целый месяц.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 30,
    },
    {
        "code": "xp_500",
        "title": "500 XP",
        "description": "Наберите первые 500 XP.",
        "icon_url": "",
        "condition_type": "total_xp",
        "condition_value": 500,
    },
    {
        "code": "xp_1500",
        "title": "1500 XP",
        "description": "Наберите 1500 XP.",
        "icon_url": "",
        "condition_type": "total_xp",
        "condition_value": 1500,
    },
    {
        "code": "learned_50",
        "title": "50 выученных слов",
        "description": "Отметьте 50 слов как выученные.",
        "icon_url": "",
        "condition_type": "learned_words",
        "condition_value": 50,
    },
]


def backfill_srs_fields(apps, schema_editor):
    UserWordProgress = apps.get_model("trainer", "UserWordProgress")
    now = django.utils.timezone.now()
    learned_next_review = now + timedelta(days=7)

    UserWordProgress.objects.filter(is_learned=True).update(
        interval=7,
        ease_factor=2.5,
        last_review=now,
        next_review=learned_next_review,
    )
    UserWordProgress.objects.filter(is_learned=False).update(
        interval=1,
        ease_factor=2.3,
        last_review=None,
        next_review=now,
    )


def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model("trainer", "Achievement")
    for item in DEFAULT_ACHIEVEMENTS:
        Achievement.objects.update_or_create(
            code=item["code"],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0002_deck_owner_userwordprogress_flashcard_known_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, default='')),
                ('condition_type', models.CharField(choices=[('first_review', 'First review'), ('streak', 'Streak'), ('total_xp', 'Total XP'), ('learned_words', 'Learned words')], max_length=32)),
                ('condition_value', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('condition_type', 'condition_value', 'title'),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_channel',
            field=models.CharField(choices=[('webhook', 'Webhook')], default='webhook', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='last_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_srs_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sessionlog',
            name='mode',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('flashcards', 'Flashcards'), ('spelling', 'Spelling'), ('review', 'Review')], max_length=32),
        ),
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('multiple_choice_correct', 'Multiple choice correct'), ('spelling_correct', 'Spelling correct'), ('review_correct', 'Review correct'), ('deck_completion', 'Deck completion')], max_length=64)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='trainer.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='trainer.word')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='trainer.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-unlocked_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
        migrations.RunPython(seed_achievements, migrations.RunPython.noop),
    ]
