DEFAULT_ACHIEVEMENTS = [
    {
        "code": "first_review",
        "title": "Первое повторение",
        "description": "Пройти первое интервальное повторение.",
        "icon_url": "",
        "condition_type": "first_review",
        "condition_value": 1,
    },
    {
        "code": "streak_3",
        "title": "Серия 3 дня",
        "description": "Заниматься 3 дня подряд.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 3,
    },
    {
        "code": "streak_7",
        "title": "Серия 7 дней",
        "description": "Заниматься 7 дней подряд.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 7,
    },
    {
        "code": "streak_30",
        "title": "Серия 30 дней",
        "description": "Заниматься 30 дней подряд.",
        "icon_url": "",
        "condition_type": "streak",
        "condition_value": 30,
    },
    {
        "code": "xp_500",
        "title": "500 XP",
        "description": "Накопить 500 очков опыта.",
        "icon_url": "",
        "condition_type": "total_xp",
        "condition_value": 500,
    },
    {
        "code": "xp_1500",
        "title": "1500 XP",
        "description": "Накопить 1500 очков опыта.",
        "icon_url": "",
        "condition_type": "total_xp",
        "condition_value": 1500,
    },
    {
        "code": "learned_50",
        "title": "50 выученных слов",
        "description": "Отметить как выученные 50 слов.",
        "icon_url": "",
        "condition_type": "learned_words",
        "condition_value": 50,
    },
]
